export enum StateEntries {
    FamilyMembersDetails = "familyMembersDetails",
    FamilyMembers = "familyMembers",
    FamilyId = "familyId",
    Notifications = "notifications",
    Uid = "uid",
    UserEmail = "userEmail",
    CurrentShoppingList = "currentShoppingList",
    ShoppingLists = "shoppingLists",
    CollaboratedShoppingLists = "collaboratedShoppingLists",
    Recipes = "recipes",
    Expenses = "expenses",
    CollaboratedPantries = "collaboratedPantries",
    CurrentPantry = "currentPantry",
    Pantries = "pantries",
    Shops = "shops",
    Newspapers = "newspapers",
}
